
print("hola Mundo".upper())
print("hola Mundo".lower())
print("hola Mundo".capitalize())
print("hola Mundo".title())
print("hola Mundo".count("o"))
print("hola Mundo".find("o"))
print("hola Mundo".rfind("o"))
print("hola mundo".isdigit())
print("12345".isdigit())
print("hola Mundo".isalnum())
print("hola123Mundo".isalnum())
print("holaMundo".isalpha())
print("holamundo".islower())
print("hola Mundo".split())
print(" ".join("hola mundo"))
